configuration: Release

install:
- GitVersion /output buildserver /UpdateAssemblyInfo true
- choco install opencover -source https://nuget.org/api/v2/
- choco install coveralls.io -source https://nuget.org/api/v2/
- choco install resharper-clt

#cache:
#- packages -> **\packages.config
#- C:\ProgramData\chocolatey\bin\OpenCover.Console.exe -> appveyor.yml
#- C:\ProgramData\chocolatey\bin\coveralls.net.exe -> appveyor.yml
#- C:\ProgramData\chocolatey\bin\inspectcode.exe -> appveyor.yml
#- C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  COVERALLS_REPO_TOKEN:
    secure: S45Gg5pKn0LcC70m7IjzcmPVcuqsdK+Uiq8kUorOfQDM1OM+7pjlcaD0eomEJrqz

build:
  project: SemanticReleaseNotesParser.sln
  verbosity: minimal

after_build:
- inspectcode /o="inspectcodereport.xml" "SemanticReleaseNotesParser.sln"
#- NVika\bin\Release\NVika buildserver "inspectcodereport.xml" --debug --includesource

test_script:
- OpenCover.Console.exe -register:user -filter:"+[SemanticReleaseNotesParser.Core]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -target:"xunit.console.clr4.exe" -targetargs:"""SemanticReleaseNotesParser.Core.Tests\bin\Release\SemanticReleaseNotesParser.Core.Tests.dll"" /noshadow /appveyor" -output:coverage.xml -returntargetcode
- coveralls.net --opencover coverage.xml
- OpenCover.Console.exe -register:user -filter:"+[SemanticReleaseNotesParser]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -target:"xunit.console.clr4.exe" -targetargs:"""SemanticReleaseNotesParser.Tests\bin\Release\SemanticReleaseNotesParser.Tests.dll"" /noshadow /appveyor" -output:coverage.xml -returntargetcode
- coveralls.net --opencover coverage.xml

artifacts:
- path: inspectcodereport.xml
- path: coverage.xml
- path: NVika\bin\Release\SemanticReleaseNotesParser.exe.CodeAnalysisLog.xml
  name: SemanticReleaseNotesParser.exe.CodeAnalysisLog.xml
- path: NVika\bin\Release\SemanticReleaseNotesParser.Core..dll.CodeAnalysisLog.xml
  name: SemanticReleaseNotesParser.Core.dll.CodeAnalysisLog.xml
