// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("SemanticReleaseNotesParser.Core")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: GuidAttribute("589794ec-4420-4b76-9b88-924d15148d51")]
[assembly: AssemblyProductAttribute("SemanticReleaseNotesParser.Core")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
